const Colors = {
  blue: '#1e00b1',
  button: '#1825ad',
  buttonPress: '#c4851c',
  buttonPressUnderlay: '#c6861d',
  darkBlue: '#18008e',
  darkGrey: '#444',
  disabled: '#ccc',
  footerActiveHighlight: '#2700eb',
  footerButtonIconColor: '#c7c6c7',
  gold: '#f5a623',
  green: '#7cd34b',
  greyText: '#9b9796',
  inputPlaceholderColor: '#bbb',
  inputTextColor: '#333',
  inputUnderline: '#bbb',
  light: '#e1e1e1',
  lightBlue: '#4c9ef5',
  lightGreen: '#d6f7C4',
  lightGrey: '#D2D2D2',
  // mainBackgroundColor: '#f3f3f3',
  mainBackgroundColor: 'white',
  navIcon: '#4c9ef5',
  navBarTitle: 'black',
  navbarColor: 'white',
  // navbarColor: '#1e00b1',
  red: '#b11e00',
  separatorColor: '#bbb',
  sky: '#c4d6f7',
  yellow: '#ffffaa',
}

export default Colors
